name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    # - name: specify NDK
    #   uses: ravinderjangra/android-ndk-toolchain-setup@0.2
    #   with:
    #     api: '21'
    #     arch: 'x86'
    #     install-location: 'toolchains'
    #     force: true
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
    - run: ./build.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Grant execute permission for gradlew
      run: |
        cd build/jsb-link/frameworks/runtime-src/proj.android-studio
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd build/jsb-link/frameworks/runtime-src/proj.android-studio
        ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: pocket_demo
        path: build/jsb-link/frameworks/runtime-src/proj.android-studio/app/build/outputs/apk/debug/PocketAdDemo-debug.apk